"use client";

import { Button, Card, CardBody } from "@heroui/react";
import Link from "next/link";

const features = [
  {
    title: "AI-Powered Quizzes",
    description: "Questions generated by GPT-4o-mini tailored to your chosen topic",
    icon: "🤖",
  },
  {
    title: "Real-Time Battles",
    description: "Challenge friends to live quiz battles with instant score sync",
    icon: "⚡",
  },
  {
    title: "Smart Explanations",
    description: "Get AI-powered explanations for every wrong answer",
    icon: "💡",
  },
  {
    title: "Leaderboard",
    description: "Compete for the top spot across all topics",
    icon: "🏆",
  },
];

export default function LandingPage() {
  return (
    <div className="min-h-screen flex flex-col items-center justify-center p-8">
      <div className="max-w-4xl w-full text-center space-y-8">
        <h1 className="text-6xl font-bold bg-gradient-to-r from-purple-500 via-pink-500 to-orange-500 bg-clip-text text-transparent">
          StudyBuddy
        </h1>
        <p className="text-xl text-default-500 max-w-2xl mx-auto">
          Challenge yourself and your friends with AI-powered quizzes.
          Pick a topic, answer questions, and climb the leaderboard.
        </p>

        <div className="flex gap-4 justify-center">
          <Button
            as={Link}
            href="/signup"
            color="primary"
            size="lg"
            variant="shadow"
          >
            Get Started
          </Button>
          <Button
            as={Link}
            href="/login"
            size="lg"
            variant="bordered"
          >
            Sign In
          </Button>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mt-12">
          {features.map((feature) => (
            <Card key={feature.title} className="bg-default-50">
              <CardBody className="text-center p-6 space-y-2">
                <span className="text-4xl">{feature.icon}</span>
                <h3 className="text-lg font-semibold">{feature.title}</h3>
                <p className="text-default-500 text-sm">{feature.description}</p>
              </CardBody>
            </Card>
          ))}
        </div>
      </div>
    </div>
  );
}
