// ============================================================
//  FILE 37 : AI — Embeddings & Semantic Search
// ============================================================
//  Topic  : text embeddings, vector representation, cosine
//           similarity, in-memory vector store, semantic search,
//           batch embedding, applications (clustering,
//           deduplication, recommendation)
//
//  WHY THIS MATTERS:
//  Traditional keyword search fails when users and documents use
//  different words for the same concept. Embeddings convert text
//  into numerical vectors that capture MEANING — "cancel tatkal
//  ticket" and "tatkal booking cancellation refund" become nearby
//  points in vector space. This is the foundation of modern
//  search, recommendation systems, and RAG (Chapter 38).
// ============================================================

// ============================================================
// STORY: IRCTC FAQ Semantic Search
// IRCTC (Indian Railway Catering and Tourism Corporation) serves
// 25 million+ passengers daily. Their FAQ section has thousands
// of entries covering booking, cancellation, tatkal quotas, RAC,
// waitlists, PNR status, and refunds. Keyword search fails
// constantly:
//   - User types: "how to cancel tatkal ticket"
//   - FAQ title is: "Tatkal Booking Cancellation & Refund Policy"
//   - Keyword search matches 0 results (different word order!)
//
// The engineering team at CRIS (Centre for Railway Information
// Systems) decides to build a semantic search system using
// embeddings. Now "cancel tatkal" finds the right FAQ because
// both texts mean the same thing — they're close in vector space
// even without keyword overlap.
// ============================================================

package main

import (
	"fmt"
	"math"
	"os"
	"sort"
	"strings"
)

// ============================================================
// SIMULATED MODE SETUP
// ============================================================

var geminiAPIKey37 = os.Getenv("GEMINI_API_KEY")
var simulatedMode37 = geminiAPIKey37 == ""

func init() {
	if simulatedMode37 {
		fmt.Println("==========================================================")
		fmt.Println("  SIMULATED MODE — GEMINI_API_KEY not set")
		fmt.Println("  Embeddings are simulated via keyword hashing.")
		fmt.Println("  Set GEMINI_API_KEY=your-key to use real Gemini API.")
		fmt.Println("==========================================================")
		fmt.Println()
	}
}

// ============================================================
// SECTION 1 — What Are Embeddings?
// ============================================================
// WHY: Before writing code, we need to understand the concept.
// An embedding is a list of numbers (a vector) that represents
// the MEANING of a piece of text. Think of it as GPS coordinates
// for meaning-space:
//
//   "train ticket"    → [0.82, 0.15, 0.91, ...]  (768 numbers)
//   "railway booking" → [0.80, 0.17, 0.89, ...]  (nearby!)
//   "pizza recipe"    → [0.12, 0.88, 0.03, ...]  (far away)
//
// ANALOGY: Imagine a giant map of India where every word has a
// location. "Mumbai" and "Bombay" are at the same spot. "Delhi"
// is nearby. "Tokyo" is far away. Embeddings do this for ALL
// text — sentences, paragraphs, documents.
//
// Key properties:
//   - Similar meanings → nearby vectors (small angle)
//   - Different meanings → distant vectors (large angle)
//   - Dimensions: typically 768 or 1536 floats
//   - Generated by models like text-embedding-004

// ──────────────────────────────────────────────────────────────
// EXAMPLE BLOCK 1 — Embedding Analogy Demonstration
// ──────────────────────────────────────────────────────────────

func demoEmbeddingConcept() {
	fmt.Println("============================================================")
	fmt.Println("DEMO 1: What Are Embeddings? (Conceptual)")
	fmt.Println("============================================================")
	fmt.Println()
	fmt.Println("  Text → Numbers that capture meaning")
	fmt.Println()
	fmt.Println("  Imagine a 2D meaning-space (real embeddings use 768D):")
	fmt.Println()
	fmt.Println("        'travel' axis")
	fmt.Println("            ^")
	fmt.Println("            |   * train ticket")
	fmt.Println("            |   * railway booking    (nearby = similar)")
	fmt.Println("            |")
	fmt.Println("            |          * flight booking")
	fmt.Println("            |")
	fmt.Println("            |")
	fmt.Println("            |                          * pizza recipe (far = different)")
	fmt.Println("            +------------------------------> 'food' axis")
	fmt.Println()
	fmt.Println("  Key insight: cosine similarity measures the ANGLE between vectors.")
	fmt.Println("  Angle ~0 = identical meaning, Angle ~90 = unrelated.")
	fmt.Println()

	// Show simulated embeddings for illustration
	pairs := []struct {
		textA, textB string
	}{
		{"cancel tatkal ticket", "tatkal booking cancellation refund"},
		{"train PNR status", "check PNR number railway"},
		{"cancel tatkal ticket", "best pizza in Delhi"},
	}

	fmt.Println("  Similarity between text pairs:")
	fmt.Println("  +--------------------------------------------+----------+")
	fmt.Println("  | Text Pair                                  | Cosine   |")
	fmt.Println("  +--------------------------------------------+----------+")
	for _, p := range pairs {
		vecA := simulateEmbedding(p.textA)
		vecB := simulateEmbedding(p.textB)
		sim := cosineSimilarity(vecA, vecB)
		labelA := p.textA
		if len(labelA) > 20 {
			labelA = labelA[:20]
		}
		labelB := p.textB
		if len(labelB) > 20 {
			labelB = labelB[:20]
		}
		label := fmt.Sprintf("'%s' vs '%s'", labelA, labelB)
		fmt.Printf("  | %-42s | %8.4f |\n", label, sim)
	}
	fmt.Println("  +--------------------------------------------+----------+")
	fmt.Println("  Higher cosine = more similar meaning.")
	fmt.Println()
}

// ============================================================
// SECTION 2 — Generating Embeddings
// ============================================================
// WHY: In production, you call an embedding model like
// text-embedding-004 which returns a 768-dimensional vector.
// Here we simulate embeddings using keyword hashing so the
// demo is self-contained and the similarity results are
// meaningful (related texts get similar vectors).

// ──────────────────────────────────────────────────────────────
// EXAMPLE BLOCK 2 — Embedding Generation (Simulated)
// ──────────────────────────────────────────────────────────────

// embeddingDim is the dimensionality of our simulated embeddings.
// Real Gemini text-embedding-004 uses 768 dimensions.
const embeddingDim = 64

// simulateEmbedding generates a deterministic embedding based on
// keywords present in the text. Related texts share keywords and
// thus produce similar vectors. This is a teaching approximation —
// real embeddings use deep neural networks with billions of params.
func simulateEmbedding(text string) []float32 {
	vec := make([]float32, embeddingDim)
	text = strings.ToLower(text)
	words := strings.Fields(text)

	// Keyword groups — words that should activate similar dimensions.
	// This mimics how a real model learns that "cancel" and "refund"
	// are semantically related.
	keywordGroups := map[string][]int{
		// Travel & railways
		"train":       {0, 1, 2},
		"railway":     {0, 1, 3},
		"ticket":      {1, 4, 5},
		"booking":     {4, 5, 6},
		"reservation": {4, 5, 7},
		"pnr":         {8, 9, 10},
		"status":      {9, 10, 11},
		"check":       {10, 11, 12},
		// Cancellation & refund
		"cancel":       {13, 14, 15},
		"cancellation": {13, 14, 16},
		"refund":       {14, 15, 17},
		"policy":       {16, 17, 18},
		// Tatkal
		"tatkal":  {19, 20, 21},
		"premium": {20, 22},
		"quota":   {21, 23},
		// Waitlist & RAC
		"waitlist":  {24, 25},
		"rac":       {25, 26},
		"confirm":   {26, 27},
		"confirmed": {26, 27},
		"berth":     {28, 29},
		"seat":      {28, 30},
		// Payment
		"payment": {31, 32},
		"pay":     {31, 33},
		"upi":     {32, 34},
		"card":    {33, 35},
		"irctc":   {36, 37},
		// General
		"how":    {38, 39},
		"what":   {39, 40},
		"get":    {40, 41},
		"find":   {41, 42},
		"help":   {42, 43},
		"number": {9, 44},
		// Food (unrelated to railways — should be distant)
		"food":   {50, 51, 52},
		"pizza":  {50, 53},
		"recipe": {51, 54},
		"cook":   {52, 55},
		"best":   {56, 57},
		"delhi":  {58, 59},
		"mumbai": {58, 60},
	}

	// Activate dimensions based on keywords found
	for _, word := range words {
		if dims, ok := keywordGroups[word]; ok {
			for _, d := range dims {
				vec[d] += 1.0
			}
		}
		// Also add a hash-based component for words not in groups
		hash := uint32(0)
		for _, ch := range word {
			hash = hash*31 + uint32(ch)
		}
		idx := int(hash % uint32(embeddingDim))
		vec[idx] += 0.3
	}

	// Normalize to unit vector (L2 normalization)
	// WHY: Cosine similarity is equivalent to dot product on unit vectors.
	// Normalizing once at creation time speeds up later searches.
	var magnitude float64
	for _, v := range vec {
		magnitude += float64(v) * float64(v)
	}
	magnitude = math.Sqrt(magnitude)
	if magnitude > 0 {
		for i := range vec {
			vec[i] = float32(float64(vec[i]) / magnitude)
		}
	}

	return vec
}

func demoEmbeddingGeneration() {
	fmt.Println("============================================================")
	fmt.Println("DEMO 2: Generating Embeddings")
	fmt.Println("============================================================")

	text := "How to cancel tatkal ticket on IRCTC?"
	vec := simulateEmbedding(text)

	fmt.Printf("  Text: %q\n", text)
	fmt.Printf("  Dimensions: %d\n", len(vec))
	fmt.Printf("  First 16 values: [")
	for i := 0; i < 16 && i < len(vec); i++ {
		if i > 0 {
			fmt.Print(", ")
		}
		fmt.Printf("%.3f", vec[i])
	}
	fmt.Println(", ...]")

	// Verify unit vector
	var mag float64
	for _, v := range vec {
		mag += float64(v) * float64(v)
	}
	fmt.Printf("  Magnitude (should be ~1.0): %.6f\n", math.Sqrt(mag))

	// In production with real Gemini SDK:
	// model := client.EmbeddingModel("text-embedding-004")
	// result, _ := model.EmbedContent(ctx, genai.Text(text))
	// vec := result.Embedding.Values  // []float32, 768 dimensions

	fmt.Println("\n  Production code pattern:")
	fmt.Println("    model := client.EmbeddingModel(\"text-embedding-004\")")
	fmt.Println("    result, err := model.EmbedContent(ctx, genai.Text(text))")
	fmt.Println("    vec := result.Embedding.Values  // []float32, 768D")
	fmt.Println()
}

// ============================================================
// SECTION 3 — Cosine Similarity
// ============================================================
// WHY: Cosine similarity measures how similar two vectors are
// by computing the cosine of the angle between them:
//
//   cos(theta) = (A . B) / (||A|| * ||B||)
//
//   - 1.0  = identical direction (same meaning)
//   - 0.0  = orthogonal (unrelated)
//   - -1.0 = opposite direction (opposite meaning)
//
// Since we L2-normalize embeddings, cosine similarity simplifies
// to just the dot product: cos(theta) = A . B

// ──────────────────────────────────────────────────────────────
// EXAMPLE BLOCK 3 — Cosine Similarity Implementation
// ──────────────────────────────────────────────────────────────

// cosineSimilarity computes the cosine of the angle between two vectors.
//
//	cos(theta) = (A . B) / (||A|| * ||B||)
//
// where:
//
//	A . B   = sum(a_i * b_i)       — dot product
//	||A||   = sqrt(sum(a_i^2))     — L2 norm / magnitude
//
// Returns 1.0 for identical directions, 0.0 for orthogonal, -1.0 for opposite.
// If either vector is zero, returns 0.0.
func cosineSimilarity(a, b []float32) float64 {
	if len(a) != len(b) {
		panic("cosineSimilarity: vectors must have same length")
	}

	var dotProduct float64  // A . B
	var magnitudeA float64  // ||A||^2
	var magnitudeB float64  // ||B||^2

	for i := 0; i < len(a); i++ {
		ai := float64(a[i])
		bi := float64(b[i])
		dotProduct += ai * bi    // sum of a_i * b_i
		magnitudeA += ai * ai    // sum of a_i^2
		magnitudeB += bi * bi    // sum of b_i^2
	}

	magnitudeA = math.Sqrt(magnitudeA) // ||A||
	magnitudeB = math.Sqrt(magnitudeB) // ||B||

	// Guard against division by zero (zero vector)
	if magnitudeA == 0 || magnitudeB == 0 {
		return 0.0
	}

	return dotProduct / (magnitudeA * magnitudeB)
}

func demoCosineSimilarity() {
	fmt.Println("============================================================")
	fmt.Println("DEMO 3: Cosine Similarity — The Math")
	fmt.Println("============================================================")

	// Simple 3D example to show the math
	fmt.Println("  Simple 3D example:")
	a := []float32{1, 0, 0}
	b := []float32{1, 0, 0}
	c := []float32{0, 1, 0}
	d := []float32{-1, 0, 0}

	fmt.Printf("  [1,0,0] vs [1,0,0] = %.2f  (identical)\n", cosineSimilarity(a, b))
	fmt.Printf("  [1,0,0] vs [0,1,0] = %.2f  (orthogonal/unrelated)\n", cosineSimilarity(a, c))
	fmt.Printf("  [1,0,0] vs [-1,0,0]= %.2f  (opposite)\n", cosineSimilarity(a, d))

	// Real-world text similarity examples
	fmt.Println("\n  IRCTC text similarity examples:")
	pairs := []struct {
		textA, textB string
		expected     string
	}{
		{"cancel tatkal ticket", "tatkal booking cancellation refund policy", "HIGH (same topic)"},
		{"train PNR status check", "check PNR number railway", "HIGH (same intent)"},
		{"how to book tatkal ticket", "tatkal reservation booking process", "HIGH (synonyms)"},
		{"cancel tatkal ticket", "train seat availability", "MEDIUM (both railway)"},
		{"cancel tatkal ticket", "best pizza recipe in Delhi", "LOW (unrelated)"},
	}

	fmt.Println("  +------------------------------------------------------+--------+----------------+")
	fmt.Println("  | Pair                                                 | Cosine | Expected       |")
	fmt.Println("  +------------------------------------------------------+--------+----------------+")
	for _, p := range pairs {
		vecA := simulateEmbedding(p.textA)
		vecB := simulateEmbedding(p.textB)
		sim := cosineSimilarity(vecA, vecB)
		aShort := p.textA
		if len(aShort) > 25 {
			aShort = aShort[:25]
		}
		bShort := p.textB
		if len(bShort) > 25 {
			bShort = bShort[:25]
		}
		label := fmt.Sprintf("'%s' vs '%s'", aShort, bShort)
		fmt.Printf("  | %-52s | %6.4f | %-14s |\n", label, sim, p.expected)
	}
	fmt.Println("  +------------------------------------------------------+--------+----------------+")
	fmt.Println()
}

// ============================================================
// SECTION 4 — In-Memory Vector Store
// ============================================================
// WHY: A vector store holds embeddings and supports similarity
// search. In production, you'd use Pinecone, Weaviate, or
// pgvector. For learning (and small datasets like IRCTC FAQs),
// a simple slice-based store with brute-force search works
// perfectly and teaches the core concepts.

// ──────────────────────────────────────────────────────────────
// EXAMPLE BLOCK 4 — Vector Store Implementation
// ──────────────────────────────────────────────────────────────

// VectorEntry stores a text alongside its embedding vector.
type VectorEntry struct {
	ID     string
	Text   string
	Vector []float32
}

// SearchResult pairs a VectorEntry with its similarity score.
type SearchResult struct {
	Entry      VectorEntry
	Similarity float64
}

// VectorStore is a simple in-memory vector database.
// WHY: This is the core abstraction behind every vector DB.
// Insert stores vectors, Search finds the nearest neighbors.
type VectorStore struct {
	entries []VectorEntry
}

// NewVectorStore creates an empty vector store.
func NewVectorStore() *VectorStore {
	return &VectorStore{
		entries: make([]VectorEntry, 0),
	}
}

// Insert adds a new entry with its pre-computed embedding.
func (vs *VectorStore) Insert(id, text string, vector []float32) {
	vs.entries = append(vs.entries, VectorEntry{
		ID:     id,
		Text:   text,
		Vector: vector,
	})
}

// Search performs brute-force nearest-neighbor search.
// Returns the top-K most similar entries to the query vector.
//
// Algorithm: O(n) scan — compute similarity with every stored vector,
// sort by similarity descending, return top K.
//
// For production scale (millions of vectors), use approximate nearest
// neighbor (ANN) algorithms: HNSW, IVF, or ScaNN.
func (vs *VectorStore) Search(queryVec []float32, topK int) []SearchResult {
	results := make([]SearchResult, 0, len(vs.entries))

	for _, entry := range vs.entries {
		sim := cosineSimilarity(queryVec, entry.Vector)
		results = append(results, SearchResult{
			Entry:      entry,
			Similarity: sim,
		})
	}

	// Sort by similarity descending
	sort.Slice(results, func(i, j int) bool {
		return results[i].Similarity > results[j].Similarity
	})

	// Return top K
	if topK > len(results) {
		topK = len(results)
	}
	return results[:topK]
}

// Size returns the number of entries in the store.
func (vs *VectorStore) Size() int {
	return len(vs.entries)
}

func demoVectorStore() {
	fmt.Println("============================================================")
	fmt.Println("DEMO 4: In-Memory Vector Store")
	fmt.Println("============================================================")

	store := NewVectorStore()

	// Insert some sample texts
	texts := []string{
		"How to book train tickets on IRCTC",
		"Cancel railway reservation online",
		"Check PNR status of train",
	}

	for i, text := range texts {
		vec := simulateEmbedding(text)
		id := fmt.Sprintf("doc-%d", i+1)
		store.Insert(id, text, vec)
		fmt.Printf("  Inserted: [%s] %q (%d dimensions)\n", id, text, len(vec))
	}

	// Search
	query := "PNR number check"
	queryVec := simulateEmbedding(query)
	results := store.Search(queryVec, 3)

	fmt.Printf("\n  Query: %q\n", query)
	fmt.Println("  Results:")
	for i, r := range results {
		fmt.Printf("    %d. [%.4f] %s\n", i+1, r.Similarity, r.Entry.Text)
	}
	fmt.Println()
}

// ============================================================
// SECTION 5 — IRCTC FAQ Search Demo
// ============================================================
// WHY: This is the full application — a realistic FAQ search
// system that IRCTC would actually build. We load real-ish FAQs,
// embed them, and search with natural language queries.

// ──────────────────────────────────────────────────────────────
// EXAMPLE BLOCK 5 — Complete IRCTC FAQ Semantic Search
// ──────────────────────────────────────────────────────────────

// FAQ represents an IRCTC frequently asked question.
type FAQ struct {
	ID       string
	Question string
	Answer   string
	Category string
}

// getIRCTCFAQs returns a realistic set of IRCTC FAQs.
func getIRCTCFAQs() []FAQ {
	return []FAQ{
		{ID: "FAQ-001", Category: "Booking",
			Question: "How to book train tickets online on IRCTC?",
			Answer:   "Visit irctc.co.in, register/login, search trains, select class, fill passenger details, and pay via UPI/card/netbanking."},
		{ID: "FAQ-002", Category: "Tatkal",
			Question: "Tatkal ticket booking timing and rules",
			Answer:   "Tatkal booking opens at 10:00 AM for AC classes and 11:00 AM for non-AC, one day before journey. Maximum 4 passengers per PNR."},
		{ID: "FAQ-003", Category: "Cancellation",
			Question: "Tatkal booking cancellation and refund policy",
			Answer:   "Confirmed tatkal tickets are non-refundable if cancelled. RAC/waitlisted tatkal tickets get refund minus clerkage charges."},
		{ID: "FAQ-004", Category: "PNR",
			Question: "How to check PNR status of railway ticket",
			Answer:   "Visit indianrail.gov.in/pnr_enquiry, enter 10-digit PNR number, or SMS 'PNR <number>' to 139."},
		{ID: "FAQ-005", Category: "Waitlist",
			Question: "What is waitlist and RAC in Indian Railways?",
			Answer:   "Waitlist means no seat allocated yet. RAC (Reservation Against Cancellation) means you share a berth. Both can get confirmed as others cancel."},
		{ID: "FAQ-006", Category: "Cancellation",
			Question: "How to cancel train ticket and get refund online",
			Answer:   "Login to IRCTC, go to Booked Ticket History, select the ticket, click Cancel, and refund is processed in 5-7 working days."},
		{ID: "FAQ-007", Category: "Booking",
			Question: "How to book wheelchair and special assistance on trains",
			Answer:   "Call 139 or visit IRCTC to request wheelchair assistance. Inform at least 24 hours before journey. Available at major stations."},
		{ID: "FAQ-008", Category: "Payment",
			Question: "IRCTC payment failed but money deducted from account",
			Answer:   "Payment will be auto-refunded in 3-5 working days. If not, file complaint on IRCTC with transaction ID. Do not book again immediately."},
		{ID: "FAQ-009", Category: "Food",
			Question: "How to order food on train via IRCTC e-catering",
			Answer:   "Visit ecatering.irctc.co.in or use the Zoop/IRCTC app. Enter PNR, select station, choose restaurant, and food is delivered at your seat."},
		{ID: "FAQ-010", Category: "Booking",
			Question: "How to book train ticket for senior citizen with concession",
			Answer:   "Senior citizens (male 60+, female 58+) get up to 50% concession. Select 'Senior Citizen' concession type during booking on IRCTC."},
		{ID: "FAQ-011", Category: "Tatkal",
			Question: "Difference between tatkal and premium tatkal quota",
			Answer:   "Tatkal has fixed charges. Premium Tatkal uses dynamic pricing — fare increases with demand. Premium tatkal has no refund under any condition."},
		{ID: "FAQ-012", Category: "Platform",
			Question: "How to find train platform number at railway station",
			Answer:   "Check NTES app, station display boards, or SMS 'SPOT <train-number>' to 139. Platform is usually assigned 2 hours before departure."},
		{ID: "FAQ-013", Category: "Booking",
			Question: "How to book general unreserved train ticket on UTS app",
			Answer:   "Download UTS (Unreserved Ticketing System) app, register with Aadhaar, select origin/destination, pay via UPI, and show QR code to TTE."},
		{ID: "FAQ-014", Category: "Complaint",
			Question: "How to file complaint about dirty train or coach",
			Answer:   "Tweet @RailMinIndia or @draboredirects, SMS to 139, or use RailMadad app. Include coach number, PNR, and photos."},
		{ID: "FAQ-015", Category: "Booking",
			Question: "How to link Aadhaar with IRCTC account for booking",
			Answer:   "Login to IRCTC, go to My Profile, click 'Link Aadhaar', enter 12-digit number, verify with OTP. Required for some concession tickets."},
		{ID: "FAQ-016", Category: "Cancellation",
			Question: "TDR filing for partially cancelled or RAC tickets",
			Answer:   "File TDR (Ticket Deposit Receipt) from Booked Ticket History on IRCTC for partially travelled, late running (3+ hours), or RAC ticket refunds."},
	}
}

func demoFAQSearch() {
	fmt.Println("============================================================")
	fmt.Println("DEMO 5: IRCTC FAQ Semantic Search (Full Demo)")
	fmt.Println("============================================================")

	// Step 1: Load FAQs
	faqs := getIRCTCFAQs()
	fmt.Printf("  Loaded %d IRCTC FAQs\n", len(faqs))

	// Step 2: Build vector store (embed each FAQ question)
	store := NewVectorStore()
	for _, faq := range faqs {
		// In production: vec = embeddingModel.EmbedContent(ctx, faq.Question)
		vec := simulateEmbedding(faq.Question + " " + faq.Answer)
		store.Insert(faq.ID, faq.Question, vec)
	}
	fmt.Printf("  Embedded and stored %d FAQ vectors (%dD each)\n\n", store.Size(), embeddingDim)

	// Step 3: Search with natural language queries
	queries := []struct {
		query   string
		context string
	}{
		{"how to cancel tatkal ticket", "User wants to cancel a tatkal booking"},
		{"money deducted but ticket not booked", "Payment failure scenario"},
		{"PNR number check karna hai", "Hinglish query — PNR check"},
		{"ordering food during train journey", "E-catering query"},
		{"old person discount on railway ticket", "Senior citizen concession"},
	}

	for _, q := range queries {
		fmt.Printf("  QUERY: %q\n", q.query)
		fmt.Printf("  Context: %s\n", q.context)

		queryVec := simulateEmbedding(q.query)
		results := store.Search(queryVec, 3) // Top 3 results

		for i, r := range results {
			// Find the full FAQ to get the answer
			var answer string
			for _, faq := range faqs {
				if faq.ID == r.Entry.ID {
					answer = faq.Answer
					if len(answer) > 80 {
						answer = answer[:80] + "..."
					}
					break
				}
			}
			marker := "  "
			if i == 0 {
				marker = "->"
			}
			fmt.Printf("  %s %d. [%.4f] [%s] %s\n", marker, i+1, r.Similarity, r.Entry.ID, r.Entry.Text)
			if i == 0 {
				fmt.Printf("        Answer: %s\n", answer)
			}
		}
		fmt.Println()
	}
}

// ============================================================
// SECTION 6 — Batch Embedding
// ============================================================
// WHY: Embedding texts one by one is slow and wasteful. The
// Gemini API supports batch embedding — send 100 texts in one
// call and get 100 vectors back. This reduces HTTP overhead
// and is essential for initial data loading.

// ──────────────────────────────────────────────────────────────
// EXAMPLE BLOCK 6 — Batch Embedding
// ──────────────────────────────────────────────────────────────

// batchEmbed generates embeddings for multiple texts at once.
// In production: model.BatchEmbedContents(ctx, batch)
func batchEmbed(texts []string) [][]float32 {
	vectors := make([][]float32, len(texts))
	for i, text := range texts {
		vectors[i] = simulateEmbedding(text)
	}
	return vectors
}

func demoBatchEmbedding() {
	fmt.Println("============================================================")
	fmt.Println("DEMO 6: Batch Embedding")
	fmt.Println("============================================================")

	texts := []string{
		"How to book Rajdhani Express tickets",
		"Shatabdi Express schedule Delhi to Agra",
		"Vande Bharat Express route and stops",
		"Garib Rath Express booking and fare",
		"Duronto Express vs Rajdhani comparison",
	}

	fmt.Printf("  Batch embedding %d texts...\n", len(texts))
	vectors := batchEmbed(texts)

	fmt.Printf("  Generated %d vectors of dimension %d\n\n", len(vectors), embeddingDim)

	// Show similarity matrix
	fmt.Println("  Similarity matrix (all train-related, should be mutually high):")
	fmt.Print("          ")
	for i := range texts {
		fmt.Printf("  T%-5d", i+1)
	}
	fmt.Println()

	for i, vecI := range vectors {
		textShort := texts[i]
		if len(textShort) > 8 {
			textShort = textShort[:8]
		}
		fmt.Printf("  T%d %-4s ", i+1, textShort)
		for _, vecJ := range vectors {
			sim := cosineSimilarity(vecI, vecJ)
			fmt.Printf("  %5.3f", sim)
		}
		fmt.Println()
	}

	// Production pattern:
	fmt.Println("\n  Production batch pattern:")
	fmt.Println("    model := client.EmbeddingModel(\"text-embedding-004\")")
	fmt.Println("    batch := model.NewBatch()")
	fmt.Println("    for _, text := range texts {")
	fmt.Println("        batch.AddContent(genai.Text(text))")
	fmt.Println("    }")
	fmt.Println("    results, err := model.BatchEmbedContents(ctx, batch)")
	fmt.Println("    // results.Embeddings[i].Values = []float32")
	fmt.Println()
}

// ============================================================
// SECTION 7 — Embedding Applications
// ============================================================
// WHY: Embeddings aren't just for search. They power clustering
// (group similar FAQs), recommendation (suggest related content),
// deduplication (find duplicate tickets), and anomaly detection
// (flag unusual queries).

// ──────────────────────────────────────────────────────────────
// EXAMPLE BLOCK 7 — Applications: Clustering & Deduplication
// ──────────────────────────────────────────────────────────────

func demoApplications() {
	fmt.Println("============================================================")
	fmt.Println("DEMO 7: Embedding Applications")
	fmt.Println("============================================================")

	// Application 1: Deduplication — find near-duplicate FAQs
	fmt.Println("  --- Application 1: Deduplication ---")
	fmt.Println("  Finding near-duplicate FAQ entries...")
	fmt.Println()

	dupCandidates := []struct {
		textA, textB string
	}{
		{"How to cancel train ticket online", "Cancel railway ticket on IRCTC website"},
		{"Check PNR status", "PNR enquiry for train ticket"},
		{"How to cancel train ticket online", "Best restaurants near Delhi station"},
	}

	threshold := 0.65
	fmt.Printf("  Duplicate threshold: cosine > %.2f\n\n", threshold)

	for _, pair := range dupCandidates {
		vecA := simulateEmbedding(pair.textA)
		vecB := simulateEmbedding(pair.textB)
		sim := cosineSimilarity(vecA, vecB)
		isDup := sim > threshold
		dupLabel := "NOT DUPLICATE"
		if isDup {
			dupLabel = "DUPLICATE"
		}
		fmt.Printf("  '%s'\n  '%s'\n  Similarity: %.4f -> %s\n\n",
			pair.textA, pair.textB, sim, dupLabel)
	}

	// Application 2: Clustering — group FAQs by semantic topic
	fmt.Println("  --- Application 2: Semantic Clustering ---")
	fmt.Println("  Grouping FAQs by meaning (not keyword)...")
	fmt.Println()

	categories := map[string][]string{
		"Booking":      {"book train ticket", "reservation online IRCTC", "tatkal booking process"},
		"Cancellation": {"cancel ticket refund", "cancellation policy railway", "TDR filing process"},
		"PNR & Status": {"PNR status check", "train running status", "check reservation status"},
	}

	for category, texts := range categories {
		fmt.Printf("  Cluster: %s\n", category)
		// Compute centroid (average vector)
		centroid := make([]float32, embeddingDim)
		vectors := make([][]float32, len(texts))
		for i, text := range texts {
			vec := simulateEmbedding(text)
			vectors[i] = vec
			for d := range centroid {
				centroid[d] += vec[d]
			}
		}
		for d := range centroid {
			centroid[d] /= float32(len(texts))
		}

		for i, text := range texts {
			sim := cosineSimilarity(vectors[i], centroid)
			fmt.Printf("    - %q (sim to centroid: %.4f)\n", text, sim)
		}
		fmt.Println()
	}

	// Application 3: Recommendation
	fmt.Println("  --- Application 3: Recommendation ---")
	fmt.Println("  User read: 'How to book tatkal ticket'")
	fmt.Println("  Recommending related FAQs...")

	store := NewVectorStore()
	relatedFAQs := []string{
		"Tatkal booking timing and rules",
		"Difference between tatkal and premium tatkal",
		"Tatkal cancellation and refund policy",
		"How to get confirmed tatkal ticket tips",
		"Senior citizen concession on railway",
		"How to order food on train",
	}
	for i, faq := range relatedFAQs {
		vec := simulateEmbedding(faq)
		store.Insert(fmt.Sprintf("rec-%d", i), faq, vec)
	}

	queryVec := simulateEmbedding("How to book tatkal ticket")
	results := store.Search(queryVec, 4)

	fmt.Println("  Top recommendations:")
	for i, r := range results {
		fmt.Printf("    %d. [%.4f] %s\n", i+1, r.Similarity, r.Entry.Text)
	}
	fmt.Println()
}

// ============================================================
// SECTION 8 — Key Takeaways
// ============================================================

func printEmbeddingTakeaways() {
	fmt.Println("============================================================")
	fmt.Println("KEY TAKEAWAYS — Embeddings & Semantic Search")
	fmt.Println("============================================================")
	fmt.Println()
	fmt.Println("  1. EMBEDDINGS = MEANING AS NUMBERS")
	fmt.Println("     - Text -> vector (768 floats for text-embedding-004)")
	fmt.Println("     - Similar meaning -> nearby vectors")
	fmt.Println()
	fmt.Println("  2. COSINE SIMILARITY")
	fmt.Println("     - cos(theta) = (A.B) / (||A|| * ||B||)")
	fmt.Println("     - 1.0 = identical, 0.0 = unrelated, -1.0 = opposite")
	fmt.Println()
	fmt.Println("  3. VECTOR STORE")
	fmt.Println("     - Insert: store text + its embedding")
	fmt.Println("     - Search: embed query, find nearest neighbors")
	fmt.Println("     - Production: Pinecone, Weaviate, pgvector, ChromaDB")
	fmt.Println()
	fmt.Println("  4. BATCH EMBEDDING")
	fmt.Println("     - Always batch for efficiency (100 texts per call)")
	fmt.Println("     - Reduces HTTP overhead and cost")
	fmt.Println()
	fmt.Println("  5. APPLICATIONS")
	fmt.Println("     - Semantic search (IRCTC FAQ)")
	fmt.Println("     - Deduplication (find near-duplicates)")
	fmt.Println("     - Clustering (group by meaning)")
	fmt.Println("     - Recommendation (suggest related content)")
	fmt.Println()
	fmt.Println("  NEXT: Chapter 38 combines embeddings + generation into RAG —")
	fmt.Println("  Retrieval-Augmented Generation for NDLI's academic search.")
	fmt.Println()
}

// ============================================================
// MAIN — Run all demos
// ============================================================

func main() {
	fmt.Println()
	fmt.Println("============================================================")
	fmt.Println("  FILE 37 : AI — Embeddings & Semantic Search (IRCTC FAQ)")
	fmt.Println("============================================================")
	fmt.Println()

	demoEmbeddingConcept()
	demoEmbeddingGeneration()
	demoCosineSimilarity()
	demoVectorStore()
	demoFAQSearch()
	demoBatchEmbedding()
	demoApplications()
	printEmbeddingTakeaways()
}
